# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(687, 516)
        MainWindow.setMinimumSize(QtCore.QSize(0, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(210, 0, 210, 23)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.img_mark_folder_button = QtWidgets.QPushButton(self.widget_2)
        self.img_mark_folder_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(12)
        self.img_mark_folder_button.setFont(font)
        self.img_mark_folder_button.setObjectName("img_mark_folder_button")
        self.verticalLayout_2.addWidget(self.img_mark_folder_button)
        self.img_mark_button = QtWidgets.QPushButton(self.widget_2)
        self.img_mark_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(12)
        self.img_mark_button.setFont(font)
        self.img_mark_button.setObjectName("img_mark_button")
        self.verticalLayout_2.addWidget(self.img_mark_button)
        self.video_predict_button = QtWidgets.QPushButton(self.widget_2)
        self.video_predict_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(12)
        self.video_predict_button.setFont(font)
        self.video_predict_button.setObjectName("video_predict_button")
        self.verticalLayout_2.addWidget(self.video_predict_button)
        self.model_fintuning_button = QtWidgets.QPushButton(self.widget_2)
        self.model_fintuning_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(12)
        self.model_fintuning_button.setFont(font)
        self.model_fintuning_button.setObjectName("model_fintuning_button")
        self.verticalLayout_2.addWidget(self.model_fintuning_button)
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt;\"> 垃圾识别分类系统</span></p></body></html>"))
        self.img_mark_folder_button.setText(_translate("MainWindow", "图像标注及处理"))
        self.img_mark_button.setText(_translate("MainWindow", "图像预测及处理"))
        self.video_predict_button.setText(_translate("MainWindow", "视频预测及处理"))
        self.model_fintuning_button.setText(_translate("MainWindow", "模型优化"))
